### PR TITLE
Dev decoder stateless

### PR DESCRIPTION
**Pull request by semigle**

### CODE REVIEW

**Comment by srgoog** [comment]
These patches provides few minor changes which are required to support video stateless decoder interface. Please take a look and let me know you feedback. Thanks!

**Comment by Gnurou** [comment]
Thanks! This LGTM, but I had to rebase and make a few changes due to conflicts with recent commits of mine. Can you take a look and confirm that this still works?

**Comment by Gnurou** [comment]
Ah, and please run `cargo fmt` on top of each commit, to make sure the health check test passes.

**Comment by semigle** [comment]
Great!! Thanks for rebase and health check. I've tested latest version and it's fine.

**Comment by Gnurou** [comment]
Thanks! Merged.

**Pull request merged**
